# Generated by Django 4.2 on 2023-04-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
    ]
